version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6
  build:
    commands:
      - dotnet restore
      #- dotnet build
      - dotnet publish ./CaptchaSolvingLambda/src/CaptchaSolvingLambda/CaptchaSolvingLambda.csproj
         -c Release -o ./CaptchaSolvingLambda/publish -p:PublishReadyToRun=false
      #- sam build
      - zip -r CaptchaSolvingLambda.zip ./CaptchaSolvingLambda/publish
  post_build:
    commands:
      #- sam package
      #   --template-file template.yml
      #   --output-template-file package.yml
      #   --s3-bucket demo-ci-cd-sam-bucket
      - sam package --s3-bucket eqm-build-artifacts --output-template-file package.yml 
        #emq-build-artifacts -- hardcoded in build-deploy-pipeline.yml
        # CaptchaSolvingLambda.zip
artifacts:
  files:
    - package.yml