version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.18.2
    commands:
      - echo "Installing dependencies..."
      - cd ./processing/src
      - npm install

  pre_build:
    commands:
      - echo "Compiling TypeScript..."
      - npm run tsc  # Assuming you have a script in package.json named "tsc" that runs the TypeScript compiler.

  build:
    commands:
      - echo "Building the project..."
      # If you have any build commands, place them here.

  post_build:
  commands:
    - echo "Packaging with SAM..."
    - sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket YOUR_S3_BUCKET_NAME
    - echo "Deploying with SAM..."
    - sam deploy --template-file packaged.yaml --stack-name YOUR_STACK_NAME --capabilities CAPABILITY_IAM


artifacts:
  files:
    - ./processing/src/lambda-deployable.zip
