version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd processing
      - npm install
      - npm install -g typescript

  build:
    commands:
      - tsc
      - mkdir output
      - cp -r dist/* output/
      - mkdir output/node_modules
      - cp -r node_modules/sharp output/node_modules/
      - cp -r node_modules/uuid output/node_modules/

  post_build:
    commands:
      - cd output
      - zip -r ../../CaptchaSolvingLambda.zip ./* #todo specify only necessary files
      #- aws s3 cp CaptchaSolvingLambda.zip s3://eqm-packages-dev/ #this caises access denied error

artifacts:
  files:
    - CaptchaSolvingLambda.zip #requires additional configuration of S3 bucket in Management Console