version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd processing
      - npm install
      - npm install -g typescript

  build:
    commands:
      - tsc
      #packing CaptchaSolvingLambda.zip
      - mkdir output
      - mkdir ./output/captchaSolving
      - cp captchaSolving/package.json output/captchaSolving/
      - cp -r dist/captchaSolving/* output/captchaSolving/
      - cd output/captchaSolving
      - npm install --production
      - zip -r ../../../CaptchaSolvingLambda.zip ./*
      - cd ../../ # go back to processing

  post_build:
    commands:
      #- aws s3 cp CaptchaSolvingLambda.zip s3://eqm-packages-dev/ #this caises access denied error

artifacts:
  files:
    - CaptchaSolvingLambda.zip #requires additional configuration of S3 bucket in Management Console