AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Environment:
    Description: Environment name (e.g., dev, prod, staging)
    Type: String
    AllowedValues:
      - dev
      - staging
      - prod
    Default: dev

Resources:
  EqmPackages:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'eqm-packages-${Environment}'

  EqmCaptchas:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'eqm-captchas-${Environment}'
  
  EqmCaptchasBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref EqmCaptchas
      PolicyDocument:
        Statement:
          - Action:
              - 's3:PutObject'
              - 's3:GetObject'
              - 's3:ListBucket'
            Resource: #!Ref EqmCaptchas won't work for S3 buckets
              - !Sub '${EqmCaptchas.Arn}/*'
              - !GetAtt EqmCaptchas.Arn
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
    DependsOn:
      - EqmCaptchas

  EqmPackagesBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref EqmPackages
      PolicyDocument:
        Statement:
          - Action:
              - 's3:PutObject'
              - 's3:GetObject'
              - 's3:ListBucket'
            Resource:
              - !Sub '${EqmPackages.Arn}/*'
              - !GetAtt EqmPackages.Arn
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
                - codepipeline.amazonaws.com
                - lambda.amazonaws.com
                - cloudformation.amazonaws.com
                - serverlessrepo.amazonaws.com
    DependsOn:
      - EqmPackages
  
Outputs:
  EqmPackagesBucketName:
    Description: "S3 Bucket name for EqmPackages"
    Value: !Ref EqmPackages
    Export:
      Name: EqmPackagesBucketName
  
  EqmCaptchasBucketName:
    Description: "S3 Bucket name for EqmCaptchas"
    Value: !Ref EqmCaptchas
    Export:
      Name: EqmCaptchasBucketName

