AWSTemplateFormatVersion: 2010-09-09

Resources:
  
  EqmCaptchas:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName:
        !Sub 
          - '${CaptchasBucketName}'
          - CaptchasBucketName: !ImportValue EqmCaptchasBucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: !ImportValue EqmCaptchaSolvingLambdaArn
