AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Environment:
    Description: Environment name (e.g., dev, prod, staging)
    Type: String
    AllowedValues:
      - dev
      - staging
      - prod
    Default: dev

Resources:
  ProcessingItemsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ProcessingItemsQueue-${Environment}

Outputs:
  QueueURL:
    Description: URL of the newly created SQS Queue
    Value:
      Ref: ProcessingItemsQueue
  QueueARN:
    Description: ARN of the newly created SQS Queue
    Value:
      Fn::GetAtt:
        - ProcessingItemsQueue
        - Arn