AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  Environment:
    Description: Environment name (e.g., dev, prod, staging)
    Type: String
    AllowedValues:
      - dev
      - staging
      - prod
    Default: dev

  CaptchaSolvingLambdaPrefix:
    Description: Name of the Lambda function
    Type: String
    Default: EqmCaptchaSolvingLambda

Resources:
  EqmCaptchaSolvingLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Sub ${CaptchaSolvingLambdaPrefix}-${Environment}
      Role: !GetAtt EqmCaptchaSolvingLambdaRole.Arn
      Code:
        S3Bucket: !Sub 
            - "${ImportedBucketName}"
            - ImportedBucketName: !ImportValue 
                Fn::Sub: EqmPackagesBucketName-${Environment}
        S3Key: EqmBuild/CaptchaSolvingLambda.zip
      Handler: rekognition-lambda.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          DB_TABLE_ARN: !ImportValue
            Fn::Sub: RekognitionResultsTableArn-${Environment}
    DependsOn:
      - EqmCaptchaSolvingLambdaRole
    
  EqmCaptchaSolvingLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub ${CaptchaSolvingLambdaPrefix}-${Environment}-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: EqmLambdaExecutionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'dynamodb:GetItem'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:UpdateItem'
                  - 'dynamodb:BatchGetItem'
                  - 'dynamodb:BatchWriteItem'
                Resource:
                  - !Sub 
                    - "${ResultsTableArn}"
                    - ResultsTableArn: !ImportValue 
                        Fn::Sub: RekognitionResultsTableArn-${Environment}
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                  - 's3:GetObject'
                  - 's3:DeleteObject'
                  - 's3:ListBucket'
                Resource:
                  - !Sub 
                    - "arn:aws:s3:::${CaptchasBucketName}"
                    - CaptchasBucketName: !ImportValue 
                        Fn::Sub: EqmCaptchasBucketName-${Environment}
                  - !Sub 
                    - "arn:aws:s3:::${CaptchasBucketName}/*"
                    - CaptchasBucketName: !ImportValue 
                        Fn::Sub: EqmCaptchasBucketName-${Environment}
              - Effect: Allow
                Action:
                  - 'rekognition:DetectText'
                  - 'rekognition:DetectLabels'
                  - 'rekognition:DetectFaces'
                  - 'rekognition:StartFaceDetection'
                  - 'rekognition:GetFaceDetection'
                Resource: '*'
                  
  EventBridgeRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: 'Event Rule for S3 Write Operations on EqmCaptchas bucket'
      EventPattern:
        source:
          - 'aws.s3'
        detail-type:
          - 'AWS API Call via CloudTrail'
        detail:
          eventName:
            - 'PutObject'
            - 'PostObject'
            - 'CompleteMultipartUpload'
          requestParameters:
            bucketName: 
              - !Sub 
                - "${ImportedBucketName}"
                - ImportedBucketName: !ImportValue 
                    Fn::Sub: EqmCaptchasBucketName-${Environment}
      State: 'ENABLED'
      Targets:
        - Arn: !GetAtt EqmCaptchaSolvingLambda.Arn
          Id: 'CaptchaSolvingTarget'
    DependsOn:
      - EqmCaptchaSolvingLambda

  PermissionForEventsToInvokeLambda:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !Ref EqmCaptchaSolvingLambda
      Action: 'lambda:InvokeFunction'
      Principal: 'events.amazonaws.com'
      SourceArn: !GetAtt EventBridgeRule.Arn

Outputs:

  EqmCaptchaSolvingLambdaArn:
    Description: "Captcha Solving Lambda ARN"
    Value: !GetAtt EqmCaptchaSolvingLambda.Arn
    Export:
      Name: EqmCaptchaSolvingLambdaArn
